### ISSUE TITLE
How to add a panel underneath tabs

### ISSUE THREAD

**Issue by slprogrp** [lstratman/EasyTabs#41]
Hi there,

Great work on getting version 2 out!!
In Chrome, when you download a file a panel appears at the bottom of the application, underneath the tabbed content.  This panel contains the download progress, and is present across all tabs, as it is underneath the tab control, which just resizes to fit above it.

How can I add a panel to the bottom of the AppContainer form that shows no matter what tab you are in because it is not in a tab, but instead is in the AppContainer form under the tab control, and have the tab control resize to fit it, in EasyTabs?

Thanks for your time.

**Comment by lstratman** [comment]
This is something specific to the implementing application rather than an EasyTabs enhancement.  You could start with implementing your tab forms to resize themselves to reduce their height to expose the bottom bar and then add something to your TitleBarTabs class to draw that panel at the bottom.  But again, this would be something that would be up for the implementing app to figure out.
